spring:
  # Test DataSource Configuration - Using H2 in-memory database
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  # Test JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # Test Redis Configuration - Disabled
  data:
    redis:
      host: localhost
      port: 6379
      
  # Test Kafka Configuration - Disabled for tests
  kafka:
    bootstrap-servers: localhost:9092
    # In tests, we typically want to disable actual message sending
    consumer:
      auto-startup: false
    producer:
      auto-startup: false

# Test JWT Configuration
jwt:
  secret: test_environment_secret_key

# Test Logging Configuration
logging:
  level:
    root: WARN
    com.gijun.backend: DEBUG
    org.hibernate.SQL: DEBUG
